services:
  build-left:
    build:
      context: .
    environment:
      SHIELD: cheakee_left
    volumes:
      - .:/keyboard
  build-right:
    build:
      context: .
    environment:
      SHIELD: cheakee_right
    volumes:
      - .:/keyboard
  build-left-debug:
    build:
      context: .
    environment:
      SHIELD: cheakee_left
      DEBUG: 1
    volumes:
      - .:/keyboard
  build-right-debug:
    build:
      context: .
    environment:
      SHIELD: cheakee_right
      DEBUG: 1
    volumes:
      - .:/keyboard
  build-reset:
    build:
      context: .
    environment:
      SHIELD: settings_reset
    volumes:
      - .:/keyboard
  
  